// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

listener http:Listener ep0 = new (9090);

service /drives on ep0 {
    # Delete navigation property worksheets for drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + ifMatch - ETag
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:NoContent (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function delete [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId](@http:Header {name: "If-Match"} string? ifMatch, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns http:NoContent|ODataErrorBadRequest|ODataErrorInternalServerError {
        return http:NO_CONTENT;
    }

    # Delete navigation property charts for drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookChartId - The unique identifier of workbookChart
    # + ifMatch - ETag
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:NoContent (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function delete [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/charts/[string workbookChartId](@http:Header {name: "If-Match"} string? ifMatch, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns http:NoContent|ODataErrorBadRequest|ODataErrorInternalServerError {
        return http:NO_CONTENT;
    }

    # Delete navigation property tables for drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookTableId - The unique identifier of workbookTable
    # + ifMatch - ETag
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:NoContent (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function delete [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/tables/[string workbookTableId](@http:Header {name: "If-Match"} string? ifMatch, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns http:NoContent|ODataErrorBadRequest|ODataErrorInternalServerError {
        return http:NO_CONTENT;
    }

    # Delete navigation property columns for drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookTableId - The unique identifier of workbookTable
    # + workbookTableColumnId - The unique identifier of workbookTableColumn
    # + ifMatch - ETag
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:NoContent (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function delete [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/tables/[string workbookTableId]/columns/[string workbookTableColumnId](@http:Header {name: "If-Match"} string? ifMatch, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns http:NoContent|ODataErrorBadRequest|ODataErrorInternalServerError {
        return http:NO_CONTENT;
    }

    # Delete navigation property rows for drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookTableId - The unique identifier of workbookTable
    # + workbookTableRowId - The unique identifier of workbookTableRow
    # + ifMatch - ETag
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:NoContent (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function delete [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/tables/[string workbookTableId]/rows/[string workbookTableRowId](@http:Header {name: "If-Match"} string? ifMatch, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns http:NoContent|ODataErrorBadRequest|ODataErrorInternalServerError {
        return http:NO_CONTENT;
    }

    # Get workbook from drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + dollarSelect - Select properties to be returned
    # + dollarExpand - Expand related entities
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:Ok (Retrieved navigation property)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function get [string driveId]/items/[string driveItemId]/workbook(@http:Query {name: "$select"} string[]? dollarSelect, @http:Query {name: "$expand"} string[]? dollarExpand, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns Workbook|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {id: "01BYE5RZYRQEQ6EJ6DVJHZDF6TYMLRQKAP"};
    }

    # Get application from drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + dollarSelect - Select properties to be returned
    # + dollarExpand - Expand related entities
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:Ok (Retrieved navigation property)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function get [string driveId]/items/[string driveItemId]/workbook/application(@http:Query {name: "$select"} string[]? dollarSelect, @http:Query {name: "$expand"} string[]? dollarExpand, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns Application|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {calculationMode: "Automatic"};
    }

    # Get worksheets from drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + dollarTop - Show only the first n items
    # + dollarSkip - Skip the first n items
    # + dollarSearch - Search items by search phrases
    # + dollarFilter - Filter items by property values
    # + dollarCount - Include count of items
    # + dollarOrderby - Order items by property values
    # + dollarSelect - Select properties to be returned
    # + dollarExpand - Expand related entities
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:Ok (Retrieved collection)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function get [string driveId]/items/[string driveItemId]/workbook/worksheets(@http:Query {name: "$top"} int? dollarTop, @http:Query {name: "$skip"} int? dollarSkip, @http:Query {name: "$search"} string? dollarSearch, @http:Query {name: "$filter"} string? dollarFilter, @http:Query {name: "$count"} boolean? dollarCount, @http:Query {name: "$orderby"} string[]? dollarOrderby, @http:Query {name: "$select"} string[]? dollarSelect, @http:Query {name: "$expand"} string[]? dollarExpand, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns WorksheetCollectionResponse|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {atOdataCount: 2, value: [{id: "{00000000-0001-0000-0000-000000000000}", name: "Sheet1", position: 0, visibility: "Visible"}, {id: "{00000000-0001-0000-0100-000000000000}", name: "Summary", position: 1, visibility: "Visible"}]};
    }

    # Get worksheets from drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + dollarSelect - Select properties to be returned
    # + dollarExpand - Expand related entities
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:Ok (Retrieved navigation property)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function get [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId](@http:Query {name: "$select"} string[]? dollarSelect, @http:Query {name: "$expand"} string[]? dollarExpand, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns Worksheet|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {id: "{00000000-0001-0000-0000-000000000000}", name: "Sheet1", position: 0, visibility: "Visible"};
    }

    # Get charts from drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + dollarTop - Show only the first n items
    # + dollarSkip - Skip the first n items
    # + dollarSearch - Search items by search phrases
    # + dollarFilter - Filter items by property values
    # + dollarCount - Include count of items
    # + dollarOrderby - Order items by property values
    # + dollarSelect - Select properties to be returned
    # + dollarExpand - Expand related entities
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:Ok (Retrieved collection)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function get [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/charts(@http:Query {name: "$top"} int? dollarTop, @http:Query {name: "$skip"} int? dollarSkip, @http:Query {name: "$search"} string? dollarSearch, @http:Query {name: "$filter"} string? dollarFilter, @http:Query {name: "$count"} boolean? dollarCount, @http:Query {name: "$orderby"} string[]? dollarOrderby, @http:Query {name: "$select"} string[]? dollarSelect, @http:Query {name: "$expand"} string[]? dollarExpand, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns ChartCollectionResponse|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {atOdataCount: 1, value: [{id: "{6F6D2F1A-0000-0000-0000-000000000000}", name: "Quarterly Revenue"}]};
    }

    # Get charts from drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookChartId - The unique identifier of workbookChart
    # + dollarSelect - Select properties to be returned
    # + dollarExpand - Expand related entities
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:Ok (Retrieved navigation property)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function get [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/charts/[string workbookChartId](@http:Query {name: "$select"} string[]? dollarSelect, @http:Query {name: "$expand"} string[]? dollarExpand, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns Chart|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {id: "{6F6D2F1A-0000-0000-0000-000000000000}", name: "Quarterly Revenue"};
    }

    resource function get [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/charts/[string workbookChartId]/[string chartFunction](@http:Header {name: "workbook-session-id"} string? workbookSessionId) returns ChartImageResponse|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {value: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="};
    }

    resource function get [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/[string rangeFunction](@http:Header {name: "workbook-session-id"} string? workbookSessionId) returns RangeResponse|ODataErrorBadRequest|ODataErrorInternalServerError {
        return <Range>{address: "Sheet1!A1:C3", addressLocal: "Sheet1!A1:C3", columnCount: 3, rowCount: 3, cellCount: 9, values: [["Region", "Quarter", "Revenue"], ["EMEA", "Q1", 15000], ["APAC", "Q1", 22500]]};
    }

    # Get tables from drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + dollarTop - Show only the first n items
    # + dollarSkip - Skip the first n items
    # + dollarSearch - Search items by search phrases
    # + dollarFilter - Filter items by property values
    # + dollarCount - Include count of items
    # + dollarOrderby - Order items by property values
    # + dollarSelect - Select properties to be returned
    # + dollarExpand - Expand related entities
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:Ok (Retrieved collection)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function get [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/tables(@http:Query {name: "$top"} int? dollarTop, @http:Query {name: "$skip"} int? dollarSkip, @http:Query {name: "$search"} string? dollarSearch, @http:Query {name: "$filter"} string? dollarFilter, @http:Query {name: "$count"} boolean? dollarCount, @http:Query {name: "$orderby"} string[]? dollarOrderby, @http:Query {name: "$select"} string[]? dollarSelect, @http:Query {name: "$expand"} string[]? dollarExpand, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns TableCollectionResponse|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {atOdataCount: 1, value: [{id: "1", name: "SalesTable", showHeaders: true, showTotals: false, showBandedRows: true, highlightFirstColumn: false}]};
    }

    # Get tables from drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookTableId - The unique identifier of workbookTable
    # + dollarSelect - Select properties to be returned
    # + dollarExpand - Expand related entities
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:Ok (Retrieved navigation property)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function get [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/tables/[string workbookTableId](@http:Query {name: "$select"} string[]? dollarSelect, @http:Query {name: "$expand"} string[]? dollarExpand, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns Table|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {id: "1", name: "SalesTable", showHeaders: true, showTotals: false, showBandedRows: true, highlightFirstColumn: false};
    }

    # Get columns from drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookTableId - The unique identifier of workbookTable
    # + dollarTop - Show only the first n items
    # + dollarSkip - Skip the first n items
    # + dollarSearch - Search items by search phrases
    # + dollarFilter - Filter items by property values
    # + dollarCount - Include count of items
    # + dollarOrderby - Order items by property values
    # + dollarSelect - Select properties to be returned
    # + dollarExpand - Expand related entities
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:Ok (Retrieved collection)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function get [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/tables/[string workbookTableId]/columns(@http:Query {name: "$top"} int? dollarTop, @http:Query {name: "$skip"} int? dollarSkip, @http:Query {name: "$search"} string? dollarSearch, @http:Query {name: "$filter"} string? dollarFilter, @http:Query {name: "$count"} boolean? dollarCount, @http:Query {name: "$orderby"} string[]? dollarOrderby, @http:Query {name: "$select"} string[]? dollarSelect, @http:Query {name: "$expand"} string[]? dollarExpand, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns TableColumnCollectionResponse|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {atOdataCount: 1, value: [{id: "1", name: "Region", index: 0, values: [["Region"], ["EMEA"], ["APAC"]]}]};
    }

    # Get rows from drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookTableId - The unique identifier of workbookTable
    # + dollarTop - Show only the first n items
    # + dollarSkip - Skip the first n items
    # + dollarSearch - Search items by search phrases
    # + dollarFilter - Filter items by property values
    # + dollarCount - Include count of items
    # + dollarOrderby - Order items by property values
    # + dollarSelect - Select properties to be returned
    # + dollarExpand - Expand related entities
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:Ok (Retrieved collection)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function get [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/tables/[string workbookTableId]/rows(@http:Query {name: "$top"} int? dollarTop, @http:Query {name: "$skip"} int? dollarSkip, @http:Query {name: "$search"} string? dollarSearch, @http:Query {name: "$filter"} string? dollarFilter, @http:Query {name: "$count"} boolean? dollarCount, @http:Query {name: "$orderby"} string[]? dollarOrderby, @http:Query {name: "$select"} string[]? dollarSelect, @http:Query {name: "$expand"} string[]? dollarExpand, @http:Header {name: "workbook-session-id"} string? workbookSessionId) returns TableRowCollectionResponse|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {atOdataCount: 1, value: [{index: 0, values: [["Q1", 15000, "EMEA"]]}]};
    }

    # Update the navigation property worksheets in drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + payload - New navigation property values 
    # + return - returns can be any of following types 
    # http:Ok (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function patch [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId](@http:Header {name: "workbook-session-id"} string? workbookSessionId, @http:Payload Worksheet payload) returns Worksheet|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {id: "{00000000-0001-0000-0000-000000000000}", name: "Sheet1", position: 0, visibility: "Visible"};
    }

    # Update the navigation property charts in drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookChartId - The unique identifier of workbookChart
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + payload - New navigation property values 
    # + return - returns can be any of following types 
    # http:Ok (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function patch [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/charts/[string workbookChartId](@http:Header {name: "workbook-session-id"} string? workbookSessionId, @http:Payload Chart payload) returns Chart|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {id: "{6F6D2F1A-0000-0000-0000-000000000000}", name: "Quarterly Revenue"};
    }

    # Update the navigation property tables in drives
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookTableId - The unique identifier of workbookTable
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + payload - New navigation property values 
    # + return - returns can be any of following types 
    # http:Ok (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function patch [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/tables/[string workbookTableId](@http:Header {name: "workbook-session-id"} string? workbookSessionId, @http:Payload Table payload) returns Table|ODataErrorBadRequest|ODataErrorInternalServerError {
        return {id: "1", name: "SalesTable", showHeaders: true, showTotals: false, showBandedRows: true, highlightFirstColumn: false};
    }

    # Invoke action calculate
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + payload - Action parameters 
    # + return - returns can be any of following types 
    # http:NoContent (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function post [string driveId]/items/[string driveItemId]/workbook/application/calculate(@http:Header {name: "workbook-session-id"} string? workbookSessionId, @http:Payload CalculateApplicationRequest payload) returns http:NoContent|ODataErrorBadRequest|ODataErrorInternalServerError {
        return http:NO_CONTENT;
    }

    # Invoke action closeSession
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:NoContent (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function post [string driveId]/items/[string driveItemId]/workbook/closeSession(@http:Header {name: "workbook-session-id"} string? workbookSessionId) returns http:NoContent|ODataErrorBadRequest|ODataErrorInternalServerError {
        return http:NO_CONTENT;
    }

    # Invoke action createSession
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + payload - Action parameters 
    # + return - returns can be any of following types 
    # http:Ok (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function post [string driveId]/items/[string driveItemId]/workbook/createSession(@http:Payload CreateSessionRequest payload) returns SessionInfoResponseOk|ODataErrorBadRequest|ODataErrorInternalServerError {
        return <SessionInfoResponseOk>{body: <SessionInfo>{id: "cluster=CLUSTER&session=SESSION&usid=USID", persistChanges: true}};
    }

    # Invoke action refreshSession
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + return - returns can be any of following types 
    # http:NoContent (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function post [string driveId]/items/[string driveItemId]/workbook/refreshSession(@http:Header {name: "workbook-session-id"} string? workbookSessionId) returns http:NoContent|ODataErrorBadRequest|ODataErrorInternalServerError {
        return http:NO_CONTENT;
    }

    # Invoke action add
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + payload - Action parameters 
    # + return - returns can be any of following types 
    # http:Ok (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function post [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/charts/add(@http:Header {name: "workbook-session-id"} string? workbookSessionId, @http:Payload AddChartRequest payload) returns AddChartResponseOk|ODataErrorBadRequest|ODataErrorInternalServerError {
        return <AddChartResponseOk>{body: <Chart>{id: "{6F6D2F1A-0000-0000-0000-000000000000}", name: "Quarterly Revenue"}};
    }

    # Invoke action add
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookTableId - The unique identifier of workbookTable
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + payload - Action parameters 
    # + return - returns can be any of following types 
    # http:Ok (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function post [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/tables/[string workbookTableId]/columns/add(@http:Header {name: "workbook-session-id"} string? workbookSessionId, @http:Payload AddColumnRequest payload) returns AddColumnResponseOk|ODataErrorBadRequest|ODataErrorInternalServerError {
        return <AddColumnResponseOk>{body: <TableColumn>{id: "1", name: "Region", index: 0, values: [["Region"], ["EMEA"], ["APAC"]]}};
    }

    # Invoke action add
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookTableId - The unique identifier of workbookTable
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + payload - Action parameters 
    # + return - returns can be any of following types 
    # http:Ok (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function post [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/tables/[string workbookTableId]/rows/add(@http:Header {name: "workbook-session-id"} string? workbookSessionId, @http:Payload AddRowRequest payload) returns TableRowOperationResponseOk|ODataErrorBadRequest|ODataErrorInternalServerError {
        return <TableRowOperationResponseOk>{body: <TableRow>{index: 0, values: [["Q1", 15000, "EMEA"]]}};
    }

    # Invoke action add
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookWorksheetId - The unique identifier of workbookWorksheet
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + payload - Action parameters 
    # + return - returns can be any of following types 
    # http:Ok (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function post [string driveId]/items/[string driveItemId]/workbook/worksheets/[string workbookWorksheetId]/tables/add(@http:Header {name: "workbook-session-id"} string? workbookSessionId, @http:Payload AddTableRequest payload) returns AddTableResponseOk|ODataErrorBadRequest|ODataErrorInternalServerError {
        return <AddTableResponseOk>{body: <Table>{id: "1", name: "SalesTable", showHeaders: true, showTotals: false, showBandedRows: true, highlightFirstColumn: false}};
    }

    # Invoke action add
    #
    # + driveId - The unique identifier of drive
    # + driveItemId - The unique identifier of driveItem
    # + workbookSessionId - Workbook session ID returned by createSession. Pass it to run the request inside a persistent or non-persistent Excel session
    # + payload - Action parameters 
    # + return - returns can be any of following types 
    # http:Ok (Success)
    # http:BadRequest (error)
    # http:InternalServerError (error)
    resource function post [string driveId]/items/[string driveItemId]/workbook/worksheets/add(@http:Header {name: "workbook-session-id"} string? workbookSessionId, @http:Payload AddWorksheetRequest payload) returns AddWorksheetResponseOk|ODataErrorBadRequest|ODataErrorInternalServerError {
        return <AddWorksheetResponseOk>{body: <Worksheet>{id: "{00000000-0001-0000-0000-000000000000}", name: "Sheet1", position: 0, visibility: "Visible"}};
    }
}

// Service-mode response types. `bal openapi --mode client` collapses 4XX/5XX to
// `error` and never emits these, so they are defined here for the mock only.
public type ODataError record {
    MainError 'error;
};

public type MainError record {
    string code;
    ErrorDetails[] details?;
    InnerError innerError?;
    string message;
    string? target?;
};

public type InnerError record {
    # Date when the error occured
    string? date?;
    # Client request Id as sent by the client application
    @jsondata:Name {value: "client-request-id"}
    string? clientRequestId?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType;
    # Request Id as tracked internally by the service
    @jsondata:Name {value: "request-id"}
    string? requestId?;
};

public type ErrorDetails record {
    string code;
    string message;
    string? target?;
};

public type ODataErrorBadRequest record {|
    *http:BadRequest;
    ODataError body;
|};

public type ODataErrorInternalServerError record {|
    *http:InternalServerError;
    ODataError body;
|};

public type SessionInfoResponseOk record {|
    *http:Ok;
    SessionInfoResponse body;
|};

public type TableRowOperationResponseOk record {|
    *http:Ok;
    TableRowOperationResponse body;
|};

public type AddChartResponseOk record {|
    *http:Ok;
    AddChartResponse body;
|};

public type AddColumnResponseOk record {|
    *http:Ok;
    AddColumnResponse body;
|};

public type AddTableResponseOk record {|
    *http:Ok;
    AddTableResponse body;
|};

public type AddWorksheetResponseOk record {|
    *http:Ok;
    AddWorksheetResponse body;
|};
