[package]
distribution = "2201.8.0"
org = "ballerinax"
name = "microsoft.excel"
version = "@toml.version@"
authors = ["Ballerina"]
export = ["microsoft.excel"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.excel"
keywords = ["Productivity/Spreadsheets", "Cost/Free", "Vendor/Microsoft"]
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
